config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  mount Rswag::Api::Engine => '/api-docs'

  get '/admin', to: redirect('/admin/short_links')

  namespace :api do
    namespace :v1 do
      resources :short_links, only: %i[index create show destroy]
    end
  end

  namespace :admin do
    resources :short_links, only: %i[index create destroy]
    get 'cleanup', to: 'short_links#cleanup'
  end

  get '/:id', to: 'admin/short_links#show'
  get 'admin/short_links/:id', to: 'admin/short_links#show', as: 'admin_short_link_show'
  root to: 'admin/short_links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/short_link.rb
# frozen_string_literal: true

class ShortLink < ApplicationRecord
  validates :original_url, uniqueness: true
  validates :short_url, uniqueness: true
  validates :password, presence: true

  default_scope -> { order(id: :asc) }
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "admin"
    include Pagy::Backend
  end
end

app/controllers/admin/short_links_controller.rb
# frozen_string_literal: true

module Admin
  class ShortLinksController < Admin::BaseController
    def create
      short_url = SecureRandom.uuid[0..5]

      short_url = SecureRandom.uuid[0..5] while ShortLink.exists?(short_url:)

      @short_link = ShortLink.new(link_params)
      @short_link.short_url = short_url
      @short_link.password = SecureRandom.hex(10)

      if @short_link.save
        respond_to do |format|
          format.js { render inline: 'location.reload();' }
        end
      else
        render json: @short_link.errors, status: :unprocessable_entity
      end
    end

    def index
      @pagy, @short_links = if params[:search].present?
                              pagy(ShortLink.where('original_url LIKE ?', "%#{params[:search]}%"), items: 5)
                            else
                              pagy(ShortLink.all, items: 5)
                            end
    end

    def show
      @short_link = ShortLink.find_by(short_url: params[:id])

      if @short_link
        @short_link.update_columns(link_opened: @short_link.link_opened + 1, link_opened_last_time_at: Time.current)

        redirect_to @short_link.original_url, allow_other_host: true
      else
        render json: { status: 'unprocessable_entity' }, status: :unprocessable_entity
      end
    end

    def destroy
      @short_link = ShortLink.find(params[:id])

      if @short_link&.destroy
        respond_to do |format|
          format.js { render inline: 'location.reload();' }
        end
      else
        render json: { status: 'unprocessable_entity' }, status: :unprocessable_entity
      end
    end

    def cleanup
      ShortLink.where('link_opened_last_time_at <= ?', Time.now - 2.months).destroy_all
      redirect_to admin_short_links_url, notice: 'Old links deleted successfully.'
    end

    private

    def link_params
      params.require(:short_link).permit(:original_url)
    end
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ApplicationController
      # TODO: authenticate!
      protect_from_forgery with: :null_session
      skip_before_action :verify_authenticity_token
    end
  end
end

app/controllers/api/v1/short_links_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ShortLinksController < Api::V1::BaseController
      def create
        short_url = SecureRandom.uuid[0..5]

        short_url = SecureRandom.uuid[0..5] while ShortLink.exists?(short_url:)

        @short_link = ShortLink.new(link_params)
        @short_link.short_url = short_url
        @short_link.password = SecureRandom.hex(10)

        if @short_link.save
          render json: @short_link, status: :created
        else
          render json: { status: 'unprocessable_entity' }, status: :unprocessable_entity
        end
      end

      def index
        @short_links = ShortLink.all
        render json: @short_links, status: :ok
      end

      def show
        @short_link = ShortLink.find_by(short_url: params[:id])

        if @short_link
          @short_link.update_columns(link_opened: @short_link.link_opened + 1, link_opened_last_time_at: Time.current)

          redirect_to @short_link.original_url, allow_other_host: true
        else
          render json: { status: 'unprocessable_entity' }, status: :unprocessable_entity
        end
      end

      def destroy
        @short_link = ShortLink.find_by(id: params[:id], password: params[:password])

        if @short_link&.destroy
          render json: { message: 'Short link is deleted' }, status: :ok
        else
          render json: { status: 'unprocessable_entity' }, status: :unprocessable_entity
        end
      end

      private

      def link_params
        params.require(:short_link).permit(:original_url)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/admin/short_links/index.html.erb
<div data-controller="short_links">
  <h1>Service: short link</h1>

  <h2>Create short link</h2>

  <%= form_with(model: ShortLink.new, url: admin_short_links_path, method: :post, local: true, remote: true) do |form| %>
    <%= form.label :original_url, 'Original URL' %>
    <%= form.text_field :original_url , required: true %>
    <%= form.submit 'Create short link' %>
  <% end %>

  <h2>Search by original url</h2>

  <%= form_with(url: admin_short_links_path, method: :get, local: true) do |form| %>
    <div>
      <%= form.label :search, 'Search' %>
      <%= form.text_field :search %>
      <%= form.submit 'Search' %>
    </div>
  <% end %>

  <% old_visit_short_links_count = ShortLink.where("link_opened_last_time_at <= ?", Time.now - 2.months).count %>
  <% if old_visit_short_links_count != 0 %>
    <p style="text-align: right; color: red">We have links with zero visiting for last 2 month</p>
    <p style="text-align: right"><%= link_to "Cleanup (#{old_visit_short_links_count}) links with zero visiting for last 2 month", admin_cleanup_path, method: :get %></p>
  <% end %>

  <table>
    <thead>
    <tr>
      <th>Id</th>
      <th>Short URL</th>
      <th>Original URL</th>
      <th>Link Opened</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @short_links.each do |short_link| %>
      <tr>
        <td><%= short_link.id %></td>
        <!-- TODO: fix updating UI visit counter when clicked on button -->
        <td><%= link_to short_link.short_url, url_for(controller: 'admin/short_links', action: 'show', id: short_link.short_url, only_path: false), target: "_blank" %></td>
        <td><%= link_to short_link.original_url, short_link.original_url, target: "_blank" %></td>
        <td><%= short_link.link_opened %></td>
        <td><%= button_to 'Delete', admin_short_link_path(short_link), method: :delete, remote: true %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% if @short_links.empty? %>
    <p>No links yet.</p>
  <% else %>
    <div>
      <span><%= pagy_nav(@pagy).html_safe %></span>
      <p class="center">Pagination (5 items per page)</p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>